# Generated by Django 3.0.8 on 2020-12-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FwwApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.AlterField(
            model_name='recipierating',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='rating'),
        ),
    ]
