# Generated by Django 3.0.8 on 2020-12-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FwwApp', '0002_auto_20201225_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipierating',
            name='rating',
            field=models.IntegerField(verbose_name='rating'),
        ),
    ]
