# Generated by Django 3.0.8 on 2020-12-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FwwApp', '0003_auto_20201225_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipierating',
            name='rating',
            field=models.IntegerField(null=True, verbose_name='rating'),
        ),
    ]
